
-- Création de la table jeunes
DROP TABLE IF EXISTS jeunes;
CREATE TABLE jeunes (
    -- Tu peux déclarer toutes les colonnes comme TEXT pour ingestion brute
    j_id TEXT,
    academie TEXT,
    boursier TEXT,
    est_boursier TEXT,
    echelon_bourse TEXT,
    code_postal TEXT,
    ville TEXT,
    date_inscription TEXT,
    niveau_etude TEXT,
    departement_etude TEXT,
    statut TEXT,
    date_maj_statut TEXT,
    type TEXT,
    cursus TEXT,
    cursus_autre TEXT,
    region_etude TEXT,
    habitant_qpv TEXT,
    moyenne_notes TEXT,
    consentement_newsletter TEXT,
    secteur_1 TEXT,
    secteur_2 TEXT,
    filiere_1 TEXT,
    filiere_2 TEXT,
    besoin_1 TEXT,
    besoins TEXT,
    besoin_postuler_present TEXT,
    besoin_decouvrir_present TEXT,
    besoin_performer_present TEXT,
    besoin_motiver_present TEXT,
    besoin_anglais_present TEXT,
    genre TEXT,
    nom_diplome TEXT,
    connu_par TEXT,
    age TEXT,
    filiere_bac TEXT,
    mention_bac TEXT,
    projection_etude TEXT,
    objectifs_annuels TEXT,
    frequence_echanges_souhaitee TEXT,
    programme TEXT,
    habitant_zrr TEXT,
    appel_validation_fait TEXT,
    etudiant_etranger TEXT,
    ase TEXT,
    passions TEXT,
    date_inscription_bam TEXT,
    raison_non_dispo TEXT,
    mail_activation_renvoye TEXT,
    sms_activation_envoye TEXT,
    connaissance_mentorat TEXT,
    etat_d_esprit TEXT,
    confiance_reussite TEXT,
    niveau_construction_projet TEXT,
    situation_familiale TEXT,
    admin_associe_id TEXT,
    appel_45j_fait TEXT,
    region TEXT,
    source TEXT,
    nb_propositions TEXT,
    a_ete_mentore TEXT,
    b_statut TEXT,
    b_annee_scolaire TEXT
);

COPY jeunes FROM '/docker-entrypoint-initdb.d/data/jeunes.csv'
DELIMITER ',' CSV HEADER;

-- Table benevoles (mentors)
DROP TABLE IF EXISTS benevoles;
CREATE TABLE benevoles (
    bv_id TEXT,
    cible TEXT,
    genre TEXT,
    region TEXT,
    statut TEXT,
    utilisateur_id TEXT,
    date_de_naissance TEXT,
    age TEXT,
    boursier TEXT,
    connu_par TEXT,
    profil_linkedin TEXT,
    passions TEXT,
    type_aide TEXT,
    departement TEXT,
    experience TEXT,
    consentement_newsletter TEXT,
    multibinome TEXT,
    date_inscription TEXT,
    charte_benevole TEXT,
    nb_binome_en_cours TEXT,
    secteur_metier TEXT,
    statut_activite TEXT,
    admin_associe_id TEXT,
    status_formation TEXT,
    date_maj_statut TEXT,
    duree_accompagnement_souhaitee TEXT,
    sans_diplome TEXT,
    raison_non_dispo TEXT,
    mail_activation_renvoye TEXT,
    sms_activation_envoye TEXT,
    cursus_recent TEXT,
    diplome_recent TEXT,
    filiere_recente TEXT,
    poste_actuel TEXT,
    secteur_actuel TEXT,
    est_entreprise_partenaire TEXT,
    nb_binomes TEXT,
    nb_annulations TEXT,
    nb_termines TEXT,
    nb_propositions TEXT,
    a_ete_mentor TEXT,
    b_statut TEXT,
    b_annee_scolaire TEXT
);

COPY benevoles FROM '/docker-entrypoint-initdb.d/data/benevoles.csv'
DELIMITER ',' CSV HEADER;

-- Table binomes
DROP TABLE IF EXISTS binomes;
CREATE TABLE binomes (
    b_id TEXT,
    bv_id TEXT,
    statut TEXT,
    admin_id TEXT,
    j_id TEXT,
    date_proposition TEXT,
    _rappel_48h TEXT,
    date_creation TEXT,
    delai_acceptation_minutes TEXT,
    date_maj_statut TEXT,
    raison_annulation TEXT,
    commentaire TEXT,
    matching_auto TEXT,
    jour_dernier_cp TEXT,
    date_prochain_cp TEXT,
    duree_binome TEXT,
    est_lance TEXT,
    annee_scolaire TEXT,
    est_en_cours TEXT
);

COPY binomes FROM '/docker-entrypoint-initdb.d/data/binomes.csv'
DELIMITER ',' CSV HEADER;
