services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - article1_network

  airflow-init:
    build:
      context: . # <-- dossier contenant le Dockerfile personnalisé
    image: article1-airflow-custom
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "article1secretkey"
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/creds/gcp_services_cloud_ad.json
    entrypoint: /bin/bash
    command: >
      -c "airflow db init && airflow users create
      --username admin
      --password article1password
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@example.com"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../article1_dbt:/opt/airflow/dbt
      - ../creds/gcp_services_cloud_ad.json:/opt/airflow/creds/gcp_services_cloud_ad.json

    networks:
      - article1_network

  webserver:
    build:
      context: .
    image: article1-airflow-custom
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "mysecretkey"
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/creds/gcp_services_cloud_ad.json
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../article1_dbt:/opt/airflow/dbt
      - ../creds/gcp_services_cloud_ad.json:/opt/airflow/creds/gcp_services_cloud_ad.json
    networks:
      - article1_network

  scheduler:
    build:
      context: .
    image: article1-airflow-custom
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/creds/gcp_services_cloud_ad.json
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../article1_dbt:/opt/airflow/dbt
      - ../creds/gcp_services_cloud_ad.json:/opt/airflow/creds/gcp_services_cloud_ad.json

    networks:
      - article1_network

volumes:
  postgres-db-volume:

networks:
  article1_network:
    external: true
